import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import { Header, Publication } from '../components';
import { cardData, CardDataType } from '../services/cardData';
import styles from '../styles/Home.module.css';
import { FaGithub, FaTelegram } from 'react-icons/fa';
import Link from 'next/link';

interface HomeInterface {
  data: CardDataType[];
}

export const getStaticProps: GetStaticProps = async () => {
  return {
    props: {
      data: cardData,
    },
  };
};

const Home: React.FC<HomeInterface> = ({ data }: HomeInterface) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>NahtanN - Projeto Estrelar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className={styles.cards}>
        {data.map(card => {
          return <Publication key={card.title} cardData={card} />;
        })}
      </main>

      <footer className={styles.footer}>
        <div className={styles.footer__wrapper}>
          <Link href="https://github.com/NahtanN">
            <a target="_blank">
              <FaGithub />
            </a>
          </Link>
          <Link href="https://t.me/RegnetShall">
            <a target="_blank">
              <FaTelegram />
            </a>
          </Link>
        </div>
      </footer>
    </div>
  );
};

export default Home;
