import type { NextPage } from 'next';
import Head from 'next/head';
import { Header, Publication } from '../components';
import styles from '../styles/Home.module.css';
import { cardData } from '../services/cardData';
import { useEffect, useState } from 'react';
import { ConnectButton } from '../components/buttons';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>NahtanN - Projeto Estrelar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className={styles.cards}>
        {cardData.map(card => {
          return <Publication key={card.title} cardData={card} />;
        })}
      </main>
    </div>
  );
};

export default Home;
